### ISSUE TITLE
Problème avec la sélection de compte

### ISSUE THREAD

**Issue by MatisGasse** [c-m-SIO/Fulbank#11]
Quand on est sur l'écran de sélection de compte et qu'on choisit un compte, celui qui s'affiche sur l'écran suivant n'est pas toujours le bon.

Merci de régler ce problème au plus vite.

**Comment by c-m-SIO** [comment]
Merci de nous avoir remonter ce problème.
Nous avons bien pris en compte votre remarque et allons corriger ce problème sous peu.

Merci pour l'attention que vous portez à notre projet.

**Comment by c-m-SIO** [comment]
Le problème a été réglé.

N'hésitez pas à nous faire part de vos autres remarques.
